-- LIFEQUEST + SUPABASE
-- Run this entire file in Supabase Dashboard -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default 'Adventurer',
  email text,
  avatar text default '🧙',
  xp integer not null default 0,
  gold integer not null default 100,
  intellect integer not null default 10,
  strength integer not null default 10,
  vitality integer not null default 10,
  creativity integer not null default 10,
  streak integer not null default 0,
  last_active_date date,
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(trim(title)) between 1 and 150),
  category text not null check (category in ('Coding','Study','Health','Personal Growth','Social')),
  description text default '',
  reward_xp integer not null default 50 check (reward_xp between 10 and 500),
  reward_gold integer not null default 10,
  attribute_gain integer not null default 1,
  status text not null default 'pending' check (status in ('pending','completed')),
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.shop_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price integer not null check (price >= 0),
  type text not null check (type in ('item','theme','badge')),
  icon text not null
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_id bigint not null references public.shop_items(id) on delete cascade,
  purchased_at timestamptz not null default now(),
  unique(user_id, item_id)
);

insert into public.shop_items (id,name,description,price,type,icon) values
(1,'XP Boost','Earn +50% XP for 1 hour.',100,'item','⭐'),
(2,'Focus Potion','Increase task efficiency.',80,'item','🧪'),
(3,'Health Potion','Restore vitality.',70,'item','🧴'),
(4,'Dark Theme','Unlock dark mode.',150,'theme','🌑'),
(5,'Forest Theme','Unlock a nature-inspired theme.',150,'theme','🌲'),
(6,'Pixel Badge','Exclusive profile badge.',200,'badge','🛡️')
on conflict (id) do nothing;

-- Create a profile automatically whenever a Supabase Auth user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, email, avatar)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', 'Adventurer'),
    new.email,
    coalesce(new.raw_user_meta_data->>'avatar', '🧙')
  )
  on conflict (id) do update
    set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- RLS
alter table public.profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.shop_items enable row level security;
alter table public.inventory enable row level security;

drop policy if exists "profiles own row" on public.profiles;
create policy "profiles own row" on public.profiles
for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "tasks own rows" on public.tasks;
create policy "tasks own rows" on public.tasks
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "shop readable" on public.shop_items;
create policy "shop readable" on public.shop_items
for select using (auth.role() = 'authenticated');

drop policy if exists "inventory own rows" on public.inventory;
create policy "inventory own rows" on public.inventory
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Server-side quest completion. The function checks ownership and updates
-- XP, gold, attributes, streak and task status atomically.
create or replace function public.complete_quest(p_task_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  t public.tasks;
  u public.profiles;
  attr text;
  before_level integer;
  after_level integer;
  new_streak integer;
  today date := current_date;
  prev date;
  reward jsonb;
  user_json jsonb;
begin
  select * into t from public.tasks
  where id = p_task_id and user_id = auth.uid()
  for update;

  if not found then
    raise exception 'Quest not found';
  end if;

  if t.status = 'completed' then
    raise exception 'Quest is already completed';
  end if;

  select * into u from public.profiles
  where id = auth.uid()
  for update;

  before_level := floor(sqrt(greatest(u.xp,0)::numeric / 100)) + 1;
  after_level := floor(sqrt(greatest(u.xp + t.reward_xp,0)::numeric / 100)) + 1;

  attr := case t.category
    when 'Coding' then 'intellect'
    when 'Study' then 'intellect'
    when 'Health' then 'strength'
    when 'Personal Growth' then 'creativity'
    when 'Social' then 'vitality'
  end;

  new_streak := u.streak;
  if u.last_active_date is distinct from today then
    if u.last_active_date = today - 1 then
      new_streak := u.streak + 1;
    else
      new_streak := 1;
    end if;
  end if;

  update public.profiles
  set
    xp = u.xp + t.reward_xp,
    gold = u.gold + t.reward_gold,
    intellect = intellect + case when attr='intellect' then t.attribute_gain else 0 end,
    strength = strength + case when attr='strength' then t.attribute_gain else 0 end,
    vitality = vitality + case when attr='vitality' then t.attribute_gain else 0 end,
    creativity = creativity + case when attr='creativity' then t.attribute_gain else 0 end,
    streak = new_streak,
    last_active_date = today
  where id = auth.uid();

  update public.tasks
  set status='completed', completed_at=now()
  where id=t.id;

  select to_jsonb(p) into user_json from public.profiles p where p.id=auth.uid();

  reward := jsonb_build_object(
    'xp', t.reward_xp,
    'gold', t.reward_gold,
    'attribute', attr,
    'attributeGain', t.attribute_gain,
    'levelUp', after_level > before_level,
    'newLevel', after_level
  );

  return jsonb_build_object('user', user_json, 'reward', reward);
end;
$$;

grant execute on function public.complete_quest(bigint) to authenticated;

-- Atomic shop purchase.
create or replace function public.buy_shop_item(p_item_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item public.shop_items;
  current_gold integer;
begin
  select * into item from public.shop_items where id=p_item_id;
  if not found then raise exception 'Item not found'; end if;

  if exists(select 1 from public.inventory where user_id=auth.uid() and item_id=item.id) then
    raise exception 'You already own this item';
  end if;

  select gold into current_gold from public.profiles where id=auth.uid() for update;
  if current_gold < item.price then raise exception 'Not enough gold'; end if;

  update public.profiles set gold=gold-item.price where id=auth.uid();
  insert into public.inventory(user_id,item_id) values(auth.uid(),item.id);

  return jsonb_build_object('message', item.name || ' purchased');
end;
$$;

grant execute on function public.buy_shop_item(bigint) to authenticated;

-- Helpful indexes.
create index if not exists tasks_user_id_idx on public.tasks(user_id);
create index if not exists tasks_status_idx on public.tasks(user_id,status);
create index if not exists inventory_user_id_idx on public.inventory(user_id);
